### ISSUE TITLE
Can we release a new version `0.11.2`?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eoc#129]
Can we release a new version `0.11.2`?

**Comment by volodya-lombrozo** [comment]
I need `--clean` option

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.0`

**Comment by yegor256** [comment]
@volodya-lombrozo it's a minor release, not a bug fix, that's why I'm calling it 0.12.0

**Comment by volodya-lombrozo** [comment]
Thanks
