### ISSUE TITLE
"Then, you write a simple EO program in hello.eo file in the current directory:"

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eoc#15]
I have to make programs on EO in any directory and add path to it through "eoc" command or in a special directory, where npm eolang package was unpacked?
I tried both variants, but had an error: "eoc" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

As said in README.md, I installed npm, jse and eolang package via npm.

**Comment by yegor256** [comment]
@MikhailLipanin try to do

```
$ npm install -g eolang
```

Then, the `eoc` command should be available in `/usr/local/bin/eoc`

**Comment by yegor256** [comment]
@MikhailLipanin I fixed the doc: 348bfa8
