### ISSUE TITLE
Add `verify` step to dataization pipeline

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eoc#205]
There is new mandatory step `verify` in EO 0.34.0. We have to add to dataization pipeline. Otherwise there's no way to compile the program

**Comment by yegor256** [comment]
@maxonfjvipon `verify` should be part of `assemble` step. I'll add it in https://github.com/objectionary/eo/pull/2711 Thus, no changes required to eoc.

**Comment by maxonfjvipon** [comment]
@yegor256 I believe solution here is `CompileMojo` that unite all necessary mojos in one mojo

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.0`

**Comment by yegor256** [comment]
@maxonfjvipon the `verify` goal is implemented
