### ISSUE TITLE
Provide `package-lock.json`

### ISSUE THREAD

**Issue by deemp** [objectionary/eoc#218]
I'm trying to build eoc from sources via [buildNpmPackage](https://nixos.org/manual/nixpkgs/stable/#javascript-tool-specific).

It requires a `package-lock.json`.

`package-lock.json` ensures collaborators use the same versions of dependencies. 

I see no reason to not include this file into the repo.

- [ ] Generate and include `package-lock.json`

**Comment by yegor256** [comment]
@deemp done
