### ISSUE TITLE
Failing to read arguments from console

### ISSUE THREAD

**Issue by potatmen** [objectionary/eoc#23]
Argument parsing from command line doesn't work, for example when I try to run `$ eoc dataize app 9` and the program is just returning the given value, I get `Error at "EOorg.EOeolang.EOerror#Δ" attribute 
Can't get(), attribute "Δ" is absent among other 3 attrs (msg, ρ, σ) and φ is absent`.

The program is: [here](https://pastebin.com/rd1p2esZ)

**Comment by maxonfjvipon** [comment]
@potatmen do `git pull` and try again, if it works you may close the issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.0`

**Comment by yegor256** [comment]
@potatmen try to use version 0.7.0. install it this way:

```
$ npm install -g eolang
```

should work

**Comment by potatmen** [comment]
@yegor256 thanks, it works now!
