### ISSUE TITLE
Add `tests` option to `unphi` command

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eoc#248]
To resolve [this problem](https://github.com/objectionary/eo/issues/2873) we need to add an option for `unphi` command that would [add extra meta](https://github.com/objectionary/eo/issues/2909) while converting phi to xmir

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.17.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.0`
