### ISSUE TITLE
--cached option for 'clean' command

### ISSUE THREAD

**Issue by yegor256** [objectionary/eoc#25]
The option `--cached` must delete `~/.eo` directory too

**Comment by yegor256** [comment]
@maxonfjvipon maybe you can help with this one too?

**Comment by maxonfjvipon** [comment]
@yegor256 I'll try it out

**Comment by maxonfjvipon** [comment]
@yegor256 I think it can be closed

**Comment by yegor256** [comment]
@maxonfjvipon thanks for your help!
