### ISSUE TITLE
Refactor function count in mvnw.js.

### ISSUE THREAD

**Issue by tanmaysharma2001** [objectionary/eoc#262]
The count function has a implicitly declared variable named ```next```. Implicit variables are being treated as global in the JavaScript. But as in the screenshot below it can be seen the variable is being used only in the count function. It should be explicitly declared. Explicitly declaring variables improves code readability and maintainability. It makes it clear to other developers that you are creating a new variable and sets expectations about its scope. 
![image](https://github.com/objectionary/eoc/assets/78191188/c77d4709-a182-415c-bbf0-2a719e3f896e)

**Comment by tanmaysharma2001** [comment]
@yegor256 can you please approve this issue?

**Comment by yegor256** [comment]
@tanmaysharma2001 why ESLint didn't catch this bug? This is the problem. Let's fix ESLint configuration first.

**Comment by tanmaysharma2001** [comment]
@yegor256 I have added the rule "no-implicit-globals" in the .eslintrc.json to warn against the implicitly declared variables and functions. Also I have added the fix for the above warning too. On making the pull request, one of the checks failed but seems to be unrelated to the fix that i have provided, so can you please run it again.
