### ISSUE TITLE
eo version 0.35.11 breaks pipelines

### ISSUE THREAD

**Issue by antonbashmakov** [objectionary/eoc#264]
Version `0.35.11` of the plugin breaks the `foreign` test. [Here](https://github.com/objectionary/eoc/actions/runs/8616832309/job/23615355830?pr=260) is an example of broken pipeline. `0.35.8` is working fine tho. 

Seems like the JSON generated by `assemble` command is broken indeed: 

`   { "id": "org.eolang.ram", "discovered": "13", "xmir": "/home/runner/work/eoc/eoc/temp/test-foreign/simple/target/1-parse/org/eolang/ram.xmir", "optimized": "/home/runner/work/eoc/eoc/temp/test-foreign/simple/target/2-optimize/org/eolang/ram.xmir", "scope": "compile", "eo": "/home/runner/work/eoc/eoc/temp/test-foreign/simple/target/4-pull/org/eolang/ram.eo", "jar": "org.eolang:eo-runtime:0.35.8", "shaken": "/home/runner/work/eoc/eoc/temp/test-foreign/simple/target/3-shake/org/eolang/ram.xmir", "version": "0.35.8", "probed": "0", "hash": "d9c8741" } ]hash": "d9c8741" } ] Unexpected token h in JSON at position 18065`

Question: Should we move this ticket to `eo` project?

**Comment by antonbashmakov** [comment]
@yegor256 I think the test could be fixed easily by providing a right JSON for the test from an asses but not from the result of `assemble` command. The purpose of the test is to test `foreign` command but not `assemble`. So the result of `assemble` is not relevant and shall be tested separately in `test_assemle`. 

I would create a right JSON for this test in order to fix the pipelines.

**Comment by yegor256** [comment]
@maxonfjvipon what do you think?

**Comment by yegor256** [comment]
@antonbashmakov the build is clean now, try again. If something fails, please submit a new ticket.
