### ISSUE TITLE
Update license copyright year (Workflow)

### ISSUE THREAD

**Issue by slry** [objectionary/eoc#275]
# Problem
The year in MIT License in files is outdated

# Solution
Update year in files and create shell script to run in Github Workflow to check year date in files

**Comment by slry** [comment]
@yegor256 can you approve this issue, please, so I start working on it?

**Comment by yegor256** [comment]
@slry definitely, please help! But we should not only update the year, but also introduce an automated check into our build pipeline, which would fail the build next year (in 2025), when the year will be outdated.
