### ISSUE TITLE
Array creating works inorrectly

### ISSUE THREAD

**Issue by potatmen** [objectionary/eoc#29]
There are two simple programs: 
```
[x y] > pair

[n m] > getArr
  * n m > @

[args...] > life
  pair 1 2 > p
  getArr p.x p.y > res
  stdout > @
    sprintf
      "%d \n"
      res.length
```
And:
```
[x y] > pair

[n m] > getArr
  * n m > @

[args...] > life
  pair 1 2 > p
  p.x > n
  p.y > m
  getArr n m > res
  stdout > @
    sprintf
      "%d \n"
      res.length
```

Both make a pair object and then pass `.x` and `.y` to the object that creates array of these two elements. In first case we pass both argument without creating new variables and in second version we make it. First program catches an error `The object is at the line #7, position #2; caused by ExUnset: Error at "EOorg.EOeolang.EOarray#x" attribute; caused by ExUnset: Can't get(), attribute "x" is absent among other 7 attrs (ρ, with, σ, at, Δ, length, concat) and φ is absent"` and the second one works without errors.
What is the problem?

**Comment by potatmen** [comment]
@yegor256 @maxonfjvipon @kerelape

**Comment by maxonfjvipon** [comment]
@potatmen try `getArr (p.x) (p.y) > res`

**Comment by potatmen** [comment]
@maxonfjvipon it works now, thanks

**Comment by maxonfjvipon** [comment]
@potatmen you also can do:
```
getArr > res
  p.x
  p.y
```
