### ISSUE TITLE
`eoc phi` doesn't work for EO 0.38.3

### ISSUE THREAD

**Issue by deemp** [objectionary/eoc#296]
Command: https://github.com/objectionary/normalizer/blob/8347f003d7269a3cbe6a05072082808206257ec2/scripts/pipeline.sh#L33

Error: https://github.com/objectionary/normalizer/actions/runs/9399384074/job/25886708460#step:13:77

Artifact: https://github.com/objectionary/normalizer/actions/runs/9399384074/artifacts/1574670815

In the artifact, the `pipeline/eo-filtered` directory contains EO files to be converted to PHI.

**Comment by deemp** [comment]
@maxonfjvipon, I tried with 0.21.1 and the pipeline failed again.

**Comment by maxonfjvipon** [comment]
@deemp temporary solution for now would be adding `--home-tag=0.38.2` flag. Should work for now, we'll fix the main problem soon

**Comment by deemp** [comment]
@maxonfjvipon, in which commands should I use this flag?

**Comment by maxonfjvipon** [comment]
@deemp you may use it in all of the commands, it should not change anything

**Comment by deemp** [comment]
@maxonfjvipon Then I get an error at `eoc test` after normalization.

https://github.com/objectionary/normalizer/actions/runs/9411899039/job/25925936537#step:13:423

**Comment by maxonfjvipon** [comment]
@deemp it seems like your normalization broke something:
```
Failed to execute goal org.eolang:eo-maven-plugin:0.38.3:assemble (default-cli) on project eoc:
'org.eolang.maven.AssembleMojo@25a7fedf' execution failed: java.lang.IllegalStateException:
 org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.PullMojo@72484e47' execution failed: java.io.IOException: 
Failed while trying to save to /home/runner/work/normalizer/normalizer/pipeline/eo-normalized/.eoc/4-pull/org/eolang/org.eo: 
EO object 'https://raw.githubusercontent.com/objectionary/home/4fab83d/objects/org/eolang/org.eo' is not found in this GitHub repository: https://github.com/objectionary/home by url: org.eolang.org. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package.
``` 

It generates object `org.eolang` as independent object but not package one so it can't be downloaded from the internet

**Comment by deemp** [comment]
@maxonfjvipon, how do I know the problematic file?

**Comment by maxonfjvipon** [comment]
@deemp you should check file `./.eoc/eo-foreign.json`, find object with id `org.eolang.org` and  check where it was discovered at

**Comment by yegor256** [comment]
@deemp still a bug?

**Comment by deemp** [comment]
@yegor256, the last runs of the pipeline were successful. I think this issue can be closed.
