### ISSUE TITLE
Cannot run eoc test

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eoc#30]
When I try to run ``` eoc test ``` in terminal, it fails. Maybe I do smth wrong, but there is a [log.txt](https://github.com/objectionary/eoc/files/9243233/log.txt) with output. Nevertheless, some programs I can run like hello.eo etc. What should I do?

**Comment by kerelape** [comment]
@ivan-egorov42 can you show the code, please?

**Comment by ivan-egorov42** [comment]
I cloned this repository to my PC and run ``` eoc test ``` in eoc folder, so I didn't have a program. But now I try to run it in folder with hello.eo and it fails again, and [log.txt](https://github.com/objectionary/eoc/files/9243398/log.txt) changed. This is my code 
```
[args...] > hello
  QQ.io.stdout > @
    "Hello, world!\n"
```
It works, when I run ```eoc dataize hello ``` and prints "Hello, world!" in terminal, but ```eoc test``` doesn't work.

I have:
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

node v16.16.0
npm  v8.15.1

**Comment by ivan-egorov42** [comment]
Misclicked on closing issue, sry.

**Comment by kerelape** [comment]
> But now I try to run it in folder with hello.eo and it fails again, and [log.txt](https://github.com/objectionary/eoc/files/9243398/log.txt) changed.

Now the build fails because "there are no tests".

**Comment by kerelape** [comment]
@ivan-egorov42 the first log you shared, was complaining about an object called `story`. This may happen when you try to use an object that is not in objectionary without an alias

**Comment by ivan-egorov42** [comment]
First log was when I run ``` eoc test ``` in folder with eoc, so I don't use any programs or objects. 

Second log says that there were no tests. I tried to add folders test and itest in folder with my program hello.eo and it seems I got the same [log.txt](https://github.com/objectionary/eoc/files/9250762/log.txt). It complains about ```story``` again and ```story.eo``` as I understand. I suppose there is a problem with tests. I even didn't use this object, I open sources and it is used there.

**Comment by ivan-egorov42** [comment]
I think it would be nice to tell user in RM that he has to add tests or maybe clone repository in his project directory if he wants to run `eoc test`? BTW, is there any solution with my problem?

**Comment by kerelape** [comment]
@ivan-egorov42 try to run this command in a directory where you only have a test (an eo file with `+junit` meta and at least one abstract object that decorates bool) and tell the result, please

**Comment by ivan-egorov42** [comment]
I should run program like this? 
```
+junit

[args...] > hello
  QQ.io.stdout > @
    "Hello, world!\n"
```

**Comment by kerelape** [comment]
@ivan-egorov42 yes, this should work

**Comment by ivan-egorov42** [comment]
Yes, it works [log.txt](https://github.com/objectionary/eoc/files/9260959/log.txt)

**Comment by yegor256** [comment]
@ivan-egorov42 I tried to improve the documentation in a53ebf2

**Comment by ivan-egorov42** [comment]
It works with hello.eo, but I still can't run your test. 

P.S. I tried to run `../src/eoc.js dataize program` from https://github.com/objectionary/eoc/blob/master/itest/README.md and get this error: [log.txt](https://github.com/objectionary/eoc/files/9267692/log.txt). I realized from this log that I should install "commander": `npm install commander`. I think it would be nice to write this in RM, because I installed Java, Node and npm as it was said in RM, but no words about some packages. Nevertheless, I still can't run `../src/eoc.js dataize program` and get this:

_Error: Could not find or load main class org.eolang.Main
Caused by: java.lang.ClassNotFoundException: org.eolang.Main_

**Comment by ivan-egorov42** [comment]
> Error: Could not find or load main class org.eolang.Main
Caused by: java.lang.ClassNotFoundException: org.eolang.Main

**Sorry, I confused erorrs, now I have this output:**

_Error at "number.as-int.ρ" attribute
Error at "EOorg.EOeolang.EOmath.EOnumber#n" attribute
Error at "number.as-float.ρ" attribute
Error at "EOorg.EOeolang.EOmath.EOnumber#n" attribute
Error at "φ.σ" attribute
Error at "EOorg.EOeolang.EOmath.EOrandom#seed" attribute
The attribute is not initialized, can't read_
