### ISSUE TITLE
Non-working simple integration test

### ISSUE THREAD

**Issue by includealex** [objectionary/eoc#32]
As written in [itest/README.md](https://github.com/objectionary/eoc/blob/master/itest/README.md), typing 
```
../src/eoc.js dataize program
```
is running a simple integration test. But that leads to non-expected errors:
```
Error at "EOorg.EOeolang.EOmath.EOnumber#n" attribute
Error at "EOorg.EOeolang.EOmath.EOnumber#n" attribute
Error at "EOorg.EOeolang.EOmath.EOrandom#seed" attribute
The attribute is not initialized, can't read
```

**Comment by yegor256** [comment]
@mximp let's try to fix this

**Comment by mximp** [comment]
@includealex what is the source of integration test? 
Or you are running sources as is from the repo?

**Comment by includealex** [comment]
@mximp I went to the [itest](https://github.com/includealex/eoc/tree/master/itest) directory. So my history of bash commands was:
```bash
cd itest
../src/eoc.js dataize program
```
But it works now and no errors are appearing.
