### ISSUE TITLE
weird message on `eoc clean`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eoc#382]
Here:

```
$ mkdir .eoc
$ eoc clean
The directory .eoc doesn't exist, no need to delete
```

The directory gets deleted all right, but why this weird message?

**Comment by mpa-LHutchinson** [comment]
Hi, could you assign this issue to me? I'll get working on it as soon as I can.

**Comment by yegor256** [comment]
@mpa-LHutchinson go ahead

**Comment by yegor256** [comment]
@mpa-LHutchinson solved, thanks!
