### ISSUE TITLE
Githook which check the files with versions and tags

### ISSUE THREAD

**Issue by trapvpack** [objectionary/eoc#407]
@yegor256 maybe we need to create some githook, which checks the files with EO versions and tags change before it pushed on remote repo (something like if a.txt has changed then b.txt should be changed too) and also add it to the CI pipeline? I think this solution should close #388

**Comment by yegor256** [comment]
@trapvpack in general, we are against githooks: https://slang.cx/pre-commit-hooks but thanks for suggesting!
