### ISSUE TITLE
User instruction for the NPM eolang package should be updated

### ISSUE THREAD

**Issue by iri** [objectionary/eoc#439]
Readme of the NPM package should be updated. (https://www.npmjs.com/package/eolang)

1. "npm install -g eolang@0.26.0" -> "npm install -g eolang@0.28.0" 

2. "eoc dataize hello" -> "eoc --easy dataize hello"

**Comment by yegor256** [comment]
@iri they are updated automatically, on ever release to npmjs

**Comment by 0crat** [comment]
@iri Thanks for submitting this ticket! However, as you see, it was not accepted by the team, which is sad. You've earned -16 points. By reporting bugs or suggesting enhacements, you help our project improve its quality. Please, don't be discouraged. Instead, try to be more careful next time, and [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs. Your running balance is [-12](https://www.eolang.org/zerocracy/objectionary-vitals.html).
