### ISSUE TITLE
build is broken due to eslint errors

### ISSUE THREAD

**Issue by yegor256** [objectionary/eoc#59]
For some weird reason, the build is broken, while locally `grunt eslint` works just fine for me and reports no issues: https://github.com/objectionary/eoc/runs/8254704962?check_suite_focus=true

**Comment by yegor256** [comment]
@Graur please, dispatch this one

**Comment by Graur** [comment]
@ivan-egorov42 please, take this task

**Comment by yegor256** [comment]
@Graur I fixed this already

**Comment by Graur** [comment]
@yegor256 Thanks!
