### ISSUE TITLE
Can not get GMI

### ISSUE THREAD

**Issue by Karina5005** [objectionary/eoc#71]
How can I get GMI for an example from README?
I tried:
```
eoc clean
eoc gmi
```
```
eoc clean
eoc dataize hello
eoc gmi
```
```
eoc clean
eoc assemble
eoc gmi
```
But everytime GMI's is not generated and in logs I have this line:
`[INFO] No .xmir converted to GMIs`

**Comment by yegor256** [comment]
@Karina5005 I just did `eoc clean && eoc gmi` and it worked just well. Try this one again and post a full log here:

```
$ eoc clean && eoc gmi --verbose
```

**Comment by yegor256** [comment]
@Karina5005 my mistake. I didn't get an error, but I didn't get any `.gmi` files either.

**Comment by yegor256** [comment]
@Karina5005 try this one, should work:

```
$ eoc gmi --include '**'
```

**Comment by Karina5005** [comment]
@yegor256 Thank you! It works so.

**Comment by yegor256** [comment]
@rultor release, tag is `0.8.6`
