### ISSUE TITLE
"[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.28.9:assemble" when running "eoc dataize hello"

### ISSUE THREAD

**Issue by EduardoFernandes1410** [objectionary/eoc#79]
When executing "eoc dataize hello" on the hello world example from README.md, I get the following error message after several minutes (provided in pastebin due to the size of it):

https://pastebin.com/TirD0i7S

node version: v16.17.1
npm version: 8.15.0
java version: 17.0.4
javac version: 17.0.4
OS: ubuntu 22.04

**Comment by kerelape** [comment]
> Failed to execute org.eolang.maven.PullMojo: Failed while trying to save to 
> ./home/eduardo/Documents/INNOPOLIS/EQSP/Project/Examples/.eoc/04-pull/org/eolang/sprintf.eo

Looks like you use `sprintf` as is. You have to either use it like `QQ.txt.sprintf`, or make and alias to it `+alias org.eolang.txt.sprintf`

**Comment by EduardoFernandes1410** [comment]
I'm using the code given as an example in the README.md of this repo. There is no sprintf, only stdout. Here is the full code:
```
[args...] > hello
  QQ.io.stdout > @
    "Hello, world!\n"
```

**Comment by yegor256** [comment]
@EduardoFernandes1410 it's a known problem, seems to be closed already: https://github.com/objectionary/eo/issues/1323
