### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Masynchin** [objectionary/eoc#81]
I want to compile `hello.eo` with the following content:

~~~eo
[args...] > hello
  QQ.io.stdout > @
    "Hello, world!\n"
~~~

I run `eoc dataize hello`, but it raises `java.lang.ClassNotFoundException: EOhello`.

<details>
<summary>
Full traceback
</summary>

~~~plain
EO version is 0.28.9
EO objects registered in /Users/maxsmirnov/Projects/eo-birds/.eoc/eo-foreign.json
EO version is 0.28.9
EO program assembled in /Users/maxsmirnov/Projects/eo-birds/.eoc
EO version is 0.28.9
Java sources generated in /Users/maxsmirnov/Projects/eo-birds/.eoc/generated-sources
EO version is 0.28.9
Java .class files compiled into /Users/maxsmirnov/Projects/eo-birds/.eoc
EO version is 0.28.9
Executable JAR created at /Users/maxsmirnov/Projects/eo-birds/.eoc/eoc.jar
Exception in thread "main" java.lang.ClassNotFoundException: EOhello
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:390)
	at java.base/java.lang.Class.forName(Class.java:381)
	at org.eolang.Main.run(Main.java:181)
	at org.eolang.Main.main(Main.java:98)
~~~

</details>

## Environment

- EOC: 0.8.6
- EO: 0.28.9
- JDK: 19
- OS: macOS 12.4

**Comment by yegor256** [comment]
@mximp I believe this problem is related to the recent changes in `PlaceMojo`. Please, take a look.

**Comment by mximp** [comment]
@Masynchin can you please try to run `eoc clean` and then repeat dataization?
Do you have several `.eo` files in the folder or single `hello.eo`?

**Comment by Masynchin** [comment]
> @Masynchin can you please try to run `eoc clean` and then repeat dataization?

Now it compiles, thanks!

> Do you have several `.eo` files in the folder or single `hello.eo`?

Singe `hello.eo`.

**Comment by mximp** [comment]
It happens from time to time when `.eoc` folder is messed up. There is no particular pattern for this hence nothing to fix at the moment. Normally `eoc clean` helps.

@Masynchin please close the issue if nothing left here.
