### ISSUE TITLE
Build is not stable due to not-long-enough timeouts

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eoc#87]
`eoc` pipelines fail quite often by timeout:
* https://github.com/objectionary/eoc/actions/runs/3288187318/jobs/5418222618#step:7:97
* https://github.com/objectionary/eoc/actions/runs/3128020253/jobs/5075333295#step:7:355

> the build is not stable due to not-long-enough timeouts. However, making them larger will be a lousy solution. Maybe you can find a better one.

https://github.com/objectionary/eoc/pull/83#issuecomment-1285185066

**Comment by yegor256** [comment]
@volodya-lombrozo definitely a bug, but I don't know what could be the right solution. Let's think about it and fix. Try it, please.

**Comment by volodya-lombrozo** [comment]
The issue blocked by [that](https://github.com/objectionary/eo/issues/1426)

**Comment by yegor256** [comment]
@volodya-lombrozo now it's pretty stable. I'll close this one. If you see similar problems in the future, please report it once again.
