### ISSUE TITLE
use spawn() instead of spawnSync()

### ISSUE THREAD

**Issue by yegor256** [objectionary/eoc#93]
At the moment, we have this code in `mvnw.js`:

```
  const result = spawnSync(
    bin,
    process.platform == 'win32' ? params.map((p) => `"${p}"`) : params,
    {
      cwd: home,
      stdio: 'inherit',
      shell: shell(),
    }
  );
```

It runs a provided `bin` command and returns its exit code. While it runs, we have no control. I suggest to replace `spawnSync` with `spawn` and check the status of the running command asynchronously. While waiting for the command to finish we can list all files in the directory and print its total count. This printing will help the user who is waiting to get a better feeling about the process.

**Comment by yegor256** [comment]
@volodya-lombrozo can you help with this?

**Comment by volodya-lombrozo** [comment]
@yegor256 I can try, just assign issue to me
