### ISSUE TITLE
Chained commands

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eoc#97]
When I run the next command it only cleans the directory:
```sh
eoc clean dataize app
```
Dataization doesn't happen. And I have to call `eoc dataize app` again. It would be useful to be able to state several `eoc` commands like `clean` and `dataize` in one line, as for me.

**Comment by volodya-lombrozo** [comment]
@yegor256 It seems that we can't implement that issue in a way we wanted to do so. I've asked about [the problem on SO](https://stackoverflow.com/questions/75259893/how-can-i-chain-commands-in-node-js-using-the-commander-library) and here is the answer from the main contributor of `commander` library:
> Commander supports subcommands, but not multiple commands at once

Other opportunities which can implement:
1. We can use `--clean` option
2. We can make `clean` command default for all other commands 

What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo the second option that you suggested is very expensive. We don't want to start from scratch every time. Instead, we want to build only the increment that was changed. The `--clean` option seems to be a better idea
