### ISSUE TITLE
`eslint` doesn't catch indents

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eoc#99]
`eslint` doesn't catch indents. In some places we can put 4, somewhere 2 and it's allowed which is wrong of course. It's important to adjust `eslint` to catch such mistakes.
The issue comes from that [PR comment](https://github.com/objectionary/eoc/pull/98#discussion_r1036660587).

**Comment by yegor256** [comment]
@volodya-lombrozo it's fixed and under control now, see f1cecaf
